--1) STUDENT 테이블을 참조하여 ST_TEMP 테이블을 만들고 모든 학생의 성적을 4.5만점 기준으로 수정하세요
CREATE TABLE ST_TEMP(SNO,SNAME,SEX,SYEAR,MAJOR,AVR) AS SELECT SNO,SNAME,SEX,SYEAR,MAJOR,(AVR*4.5/4.0) FROM STUDENT ;



--2) PROFESSOR 테이블을 참조하여 PF_TEMP 테이블을 만들고 모든 교수의 부임일자를 100일 앞으로 수정하세요
CREATE TABLE PE_TEMP(PNO,PNAME,SECTION,ORDERS,HIREDATE) AS SELECT PNO,PNAME,SECTION,ORDERS,HIREDATE-100  FROM PROFESSOR ;


--3) ST_TEMP 테이블에서 화학과 2학년 학생의 정보를 삭제하세요
SELECT * FROM ST_TEMP st ;
DELETE FROM ST_TEMP WHERE SYEAR = 2 AND MAJOR = '화학';
SELECT * FROM ST_TEMP st ;

--4) PF_TEMP 테이블에서 조교수의 정보를 삭제하세요
SELECT * FROM PE_TEMP st ;
DELETE FROM PE_TEMP WHERE ORDERS = '조교수';
SELECT * FROM PE_TEMP st ;

--5) EMP 테이블을 참조하여 EMP2 테이블을 만들고 
--   DNO = 30인 사원의 급여를 15프로 상승시킨 값으로 변경하세요.
--   DNO = 10인 사원의 급여를 5프로 상승시킨 값으로 변경하세요.
--   DNO = 20인 사원의 급여를 10프로 상승시킨 값으로 변경하세요.
CREATE TABLE EMP2 AS 
SELECT * FROM EMP ;
SELECT *
FROM EMP2;
UPDATE EMP2 
SET COMM= COMM*1.15
WHERE DNO = '30';
UPDATE EMP2 
SET COMM= COMM*1.05
WHERE DNO = '10';
UPDATE EMP2 
SET SAL= SAL*1.1
WHERE DNO = '20';
SELECT *
FROM EMP2;

-- 6) 화학과 2학년 학생중 기말고사 성적의 등급이 A, B인 정보를 갖는 테이블 SCORE_STGR을 생성하세요.(SNO, SNAME, MAJOR, SYEAR,CNO,CNAME, RESULT, GRADE)
CREATE TABLE SCORE_STGR AS 
SELECT ST.SNO
      ,ST.SNAME
      ,ST.MAJOR
      ,ST.SYEAR
      ,C.CNO
      ,C.CNAME
      ,SC.RESULT
      ,SR.GRADE
FROM STUDENT ST
JOIN SCORE SC
ON ST.SNO = SC.SNO
JOIN COURSE C
ON C.CNO=SC.CNO
JOIN SCGRADE SR
ON SC.RESULT BETWEEN SR.LOSCORE AND HISCORE
WHERE SR.GRADE IN ('A','B') AND ST.MAJOR ='화학' AND ST.SYEAR=2;

--7) 생물학과 학생중 평점이 2.7이상인 학생이 수강중인 과목의 정보를 갖는 테이블 ST_COURSEPF를 생성하세요. (SNO, SNAME, CNO, CNAME, PNO, PNAME, AVR)
CREATE TABLE ST_COURSEPF AS 
SELECT ST.SNO
      ,ST.SNAME
      ,C.CNO
      ,C.CNAME
      ,P.PNO
      ,P.PNAME
      ,ST.AVR
FROM STUDENT ST
JOIN SCORE SC
ON ST.SNO=SC.SNO
JOIN COURSE C
ON SC.CNO=C.CNO
JOIN PROFESSOR P
ON P.PNO = C.PNO
WHERE ST.AVR >= 2.7;